apiVersion: v1
kind: Pod-config
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      valueFrom: 
        configMapKeyRef:
          name: nginx-config
          key: course 
    - name: DURATION
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: duration
    # envFrom:
    # - configMapRef:
    #     name: nginx-config