apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      valueFrom: 
        configMapKeyRef:
          name: nginx-config #name of the configmap you want to refer
          key: course # env.name and configmap key name can be different 
    - name: DURATION
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: duration
    # envFrom:
    # - configMapRef:
    #     name: nginx-config